BEGIN TRANSACTION;
INSERT INTO "users" VALUES (1,'mrs','b21dabb4c22d87c7e22f179206f3fa06efe0e6379df60ee5cfca87bea6efd236','Сашко','2,1'); --Пароль mrs
INSERT INTO "users" VALUES (2,'s0fko','a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3','Софійка',NULL); --Пароль 123
INSERT INTO "commands" VALUES (1,'Command 1',1,'3,4');
INSERT INTO "commands" VALUES (2,'Command 2',2,NULL);
INSERT INTO "commands_user" VALUES (1,1);
INSERT INTO "commands_user" VALUES (1,2);
INSERT INTO "commands_user" VALUES (2,1);
INSERT INTO "commands_user" VALUES (2,2);
INSERT INTO "groups" VALUES (1,'Група 1 команди 1','1',1,1,0,NULL);
INSERT INTO "groups" VALUES (2,'Група 2 команди 1','1',1,2,0,NULL);
INSERT INTO "groups_user" VALUES (1,1);
INSERT INTO "groups_user" VALUES (1,2);
INSERT INTO "groups_user" VALUES (2,1);
INSERT INTO "groups_user" VALUES (2,2);
INSERT INTO "cols" VALUES (1,'Розподілено');
INSERT INTO "cols" VALUES (2,'Виконується');
INSERT INTO "cols" VALUES (3,'1 колонка 1 команди');
INSERT INTO "cols" VALUES (4,'2 колонка 1 команди');
INSERT INTO "personal_tasks" VALUES (1,'Оце таке чудове перше завдання',NULL,NULL,0,1,1);
INSERT INTO "personal_tasks" VALUES (2,'Завдання 2',NULL,NULL,0,1,1);
INSERT INTO "personal_tasks" VALUES (3,'Поїсти',NULL,NULL,0,1,2);
INSERT INTO "tasks" VALUES (1,'1 завдання 1 команди',NULL,NULL,0,1,3);
INSERT INTO "tasks" VALUES (2,'2 завдання 2 команди',NULL,NULL,0,2,4);
INSERT INTO "commands_task" VALUES (1,1);
INSERT INTO "commands_task" VALUES (2,1);

/*для тесту видалення команди*/
INSERT INTO "commands" VALUES (3,'Command 4 del',1,'5,6');
INSERT INTO "commands_user" VALUES (1,3);
INSERT INTO "cols" VALUES (5,'colonka1');
INSERT INTO "cols" VALUES (6,'colonka2');
INSERT INTO "tasks" VALUES (3,'huyask1',NULL,NULL,0,2,5);
INSERT INTO "tasks" VALUES (4,'huyask2',NULL,NULL,0,2,5);
INSERT INTO "tasks" VALUES (5,'huyask3',NULL,NULL,0,2,6);
INSERT INTO "tasks" VALUES (6,'huyask4',NULL,NULL,0,2,6);
INSERT INTO "commands_task" VALUES (3,3);
INSERT INTO "commands_task" VALUES (4,3);
INSERT INTO "commands_task" VALUES (5,3);
INSERT INTO "commands_task" VALUES (6,3);
INSERT INTO "events" VALUES (1,'event1',454545454545);
INSERT INTO "events" VALUES (2,'event2',454545454545);
INSERT INTO "commands_event" VALUES (1,3);
INSERT INTO "commands_event" VALUES (2,3);

INSERT INTO "groups" VALUES (3,'Group 3','1',3,1,0,'7,8');
INSERT INTO "groups" VALUES (4,'Group 4','1',3,1,0,'9,10');
INSERT INTO "groups_user" VALUES (1,3);
INSERT INTO "groups_user" VALUES (2,3);
INSERT INTO "groups_user" VALUES (1,4);
INSERT INTO "groups_user" VALUES (2,4);
INSERT INTO "cols" VALUES (7,'colonka3');
INSERT INTO "cols" VALUES (8,'colonka4');
INSERT INTO "cols" VALUES (9,'colonka5');
INSERT INTO "cols" VALUES (10,'colonka6');
INSERT INTO "tasks" VALUES (7,'huyask5',NULL,NULL,0,2,7);
INSERT INTO "tasks" VALUES (8,'huyask6',NULL,NULL,0,2,7);
INSERT INTO "tasks" VALUES (9,'huyask7',NULL,NULL,0,2,8);
INSERT INTO "tasks" VALUES (10,'huyask8',NULL,NULL,0,2,8);
INSERT INTO "tasks" VALUES (11,'huyask9',NULL,NULL,0,2,9);
INSERT INTO "tasks" VALUES (12,'huyask10',NULL,NULL,0,2,9);
INSERT INTO "tasks" VALUES (13,'huyask11',NULL,NULL,0,2,10);
INSERT INTO "tasks" VALUES (14,'huyask12',NULL,NULL,0,2,10);
INSERT INTO "groups_task" VALUES (7,3);
INSERT INTO "groups_task" VALUES (8,3);
INSERT INTO "groups_task" VALUES (9,3);
INSERT INTO "groups_task" VALUES (10,3);
INSERT INTO "groups_task" VALUES (11,4);
INSERT INTO "groups_task" VALUES (12,4);
INSERT INTO "groups_task" VALUES (13,4);
INSERT INTO "groups_task" VALUES (14,4);
INSERT INTO "events" VALUES (3,'event3',454545454544);
INSERT INTO "events" VALUES (4,'event4',454545454547);
INSERT INTO "groups_event" VALUES (3,3);
INSERT INTO "groups_event" VALUES (4,4);
/*INSERT INTO "groups_task" VALUES (3,1);
INSERT INTO "groups_task" VALUES (4,1);*/
COMMIT;
